### ISSUE TITLE
Obtaining modhash

### ISSUE THREAD

**Issue by alajpie** [Ajedi32/reddit_place_api#1]
>https://github.com/Ajedi32/reddit_place_api/blob/master/api.js#L99
    // \`modhash\` is a value required by Reddit as a measure to prevent CSRF attacks.
    // Ideally we'd obtain that value automatically, but I'm not really sure how to
    // do that just yet.

You can obtain the modhash on https://www.reddit.com/api/me.json
Hope this helps 😄

**Comment by Ajedi32** [comment]
Thanks. I think I saw a Python script that did basically that: https://www.reddit.com/r/Python/comments/62ph3u/python_rplace_module/
